steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - gcloud
  - functions
  - deploy
  - --allow-unauthenticated
  - cloudBuildTest
  - --memory=512MB
  - --entry-point=cloud_build_test
  - --region=asia-northeast1
  - --source=.
  - --trigger-http
  - --runtime=nodejs16