steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - --allow-unauthenticated
  - cloudBuildTest
  - --memory=512MB
  - --entry-point=cloud_build_test
  - --region=asia-northeast1
  - --source=.
  - --trigger-http
  - --runtime=nodejs16

- name: 'allow-unauthenticated'
  args:
  - gcloud alpha 
  - functions 
  - add-iam-policy-binding 
  - cloudBuildTest 
  - --region=asia-northeast1 
  - --member=allUsers 
  - --role=roles/cloudfunctions.invoker