steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - cloudbuildtest
  - --region=asia-northeast1
  - --source=.
  - --trigger-http
  - --runtime=nodejs16
  - --entry-point helloWorld